# Generated by Django 2.2 on 2020-08-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='answers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of answers'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='body',
            field=models.CharField(blank=True, help_text="text which must appear in returned questions' bodies.", max_length=1023),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='max_date',
            field=models.DateField(blank=True, null=True, verbose_name='max'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='min_date',
            field=models.DateField(blank=True, null=True, verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Page number'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='pagesize',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Page Size'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='q',
            field=models.CharField(blank=True, max_length=1023, verbose_name='q'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id of user'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='views',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum number of views'),
        ),
    ]
